# Generated by Django 3.2.6 on 2021-09-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
